package com.ruoyi.traces.domain;

public class TraceTask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trace_task.task_id
     *
     * @mbg.generated Mon Nov 09 12:11:25 CST 2020
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trace_task.crops_id
     *
     * @mbg.generated Mon Nov 09 12:11:25 CST 2020
     */
    private String cropsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trace_task.task_name
     *
     * @mbg.generated Mon Nov 09 12:11:25 CST 2020
     */
    private String taskName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trace_task.leader_id
     *
     * @mbg.generated Mon Nov 09 12:11:25 CST 2020
     */
    private String leaderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trace_task.leader_name
     *
     * @mbg.generated Mon Nov 09 12:11:25 CST 2020
     */
    private String leaderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trace_task.time
     *
     * @mbg.generated Mon Nov 09 12:11:25 CST 2020
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trace_task.status
     *
     * @mbg.generated Mon Nov 09 12:11:25 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trace_task.task_remark
     *
     * @mbg.generated Mon Nov 09 12:11:25 CST 2020
     */
    private String taskRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trace_task.task_id
     *
     * @return the value of trace_task.task_id
     *
     * @mbg.generated Mon Nov 09 12:11:25 CST 2020
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trace_task.task_id
     *
     * @param taskId the value for trace_task.task_id
     *
     * @mbg.generated Mon Nov 09 12:11:25 CST 2020
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trace_task.crops_id
     *
     * @return the value of trace_task.crops_id
     *
     * @mbg.generated Mon Nov 09 12:11:25 CST 2020
     */
    public String getCropsId() {
        return cropsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trace_task.crops_id
     *
     * @param cropsId the value for trace_task.crops_id
     *
     * @mbg.generated Mon Nov 09 12:11:25 CST 2020
     */
    public void setCropsId(String cropsId) {
        this.cropsId = cropsId == null ? null : cropsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trace_task.task_name
     *
     * @return the value of trace_task.task_name
     *
     * @mbg.generated Mon Nov 09 12:11:25 CST 2020
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trace_task.task_name
     *
     * @param taskName the value for trace_task.task_name
     *
     * @mbg.generated Mon Nov 09 12:11:25 CST 2020
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trace_task.leader_id
     *
     * @return the value of trace_task.leader_id
     *
     * @mbg.generated Mon Nov 09 12:11:25 CST 2020
     */
    public String getLeaderId() {
        return leaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trace_task.leader_id
     *
     * @param leaderId the value for trace_task.leader_id
     *
     * @mbg.generated Mon Nov 09 12:11:25 CST 2020
     */
    public void setLeaderId(String leaderId) {
        this.leaderId = leaderId == null ? null : leaderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trace_task.leader_name
     *
     * @return the value of trace_task.leader_name
     *
     * @mbg.generated Mon Nov 09 12:11:25 CST 2020
     */
    public String getLeaderName() {
        return leaderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trace_task.leader_name
     *
     * @param leaderName the value for trace_task.leader_name
     *
     * @mbg.generated Mon Nov 09 12:11:25 CST 2020
     */
    public void setLeaderName(String leaderName) {
        this.leaderName = leaderName == null ? null : leaderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trace_task.time
     *
     * @return the value of trace_task.time
     *
     * @mbg.generated Mon Nov 09 12:11:25 CST 2020
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trace_task.time
     *
     * @param time the value for trace_task.time
     *
     * @mbg.generated Mon Nov 09 12:11:25 CST 2020
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trace_task.status
     *
     * @return the value of trace_task.status
     *
     * @mbg.generated Mon Nov 09 12:11:25 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trace_task.status
     *
     * @param status the value for trace_task.status
     *
     * @mbg.generated Mon Nov 09 12:11:25 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trace_task.task_remark
     *
     * @return the value of trace_task.task_remark
     *
     * @mbg.generated Mon Nov 09 12:11:25 CST 2020
     */
    public String getTaskRemark() {
        return taskRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trace_task.task_remark
     *
     * @param taskRemark the value for trace_task.task_remark
     *
     * @mbg.generated Mon Nov 09 12:11:25 CST 2020
     */
    public void setTaskRemark(String taskRemark) {
        this.taskRemark = taskRemark == null ? null : taskRemark.trim();
    }
}