package com.ruoyi.traces.domain;

import java.util.Date;

public class TraceTransport {

    private Long id;

    private String cropsId;

    private String driverId;

    private Date time;

    private String farmerNickName;

    private String farmerUserName;

    private String farmerTel;

    private String farmerDept;

    private Integer status;

    private Integer outFactoryStatus;

    private Integer factoryId;

    private String remarks;

    public Integer getFactoryId() {
        return factoryId;
    }

    public void setFactoryId(Integer factoryId) {
        this.factoryId = factoryId;
    }

    public Integer getOutFactoryStatus() {
        return outFactoryStatus;
    }

    public void setOutFactoryStatus(Integer outFactoryStatus) {
        this.outFactoryStatus = outFactoryStatus;
    }

    public String getFarmerTel() {
        return farmerTel;
    }

    public void setFarmerTel(String farmerTel) {
        this.farmerTel = farmerTel;
    }

    public String getFarmerDept() {
        return farmerDept;
    }

    public void setFarmerDept(String farmerDept) {
        this.farmerDept = farmerDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trace_transport.id
     *
     * @return the value of trace_transport.id
     *
     * @mbg.generated Tue Nov 03 22:03:31 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trace_transport.id
     *
     * @param id the value for trace_transport.id
     *
     * @mbg.generated Tue Nov 03 22:03:31 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trace_transport.crops_id
     *
     * @return the value of trace_transport.crops_id
     *
     * @mbg.generated Tue Nov 03 22:03:31 CST 2020
     */
    public String getCropsId() {
        return cropsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trace_transport.crops_id
     *
     * @param cropsId the value for trace_transport.crops_id
     *
     * @mbg.generated Tue Nov 03 22:03:31 CST 2020
     */
    public void setCropsId(String cropsId) {
        this.cropsId = cropsId == null ? null : cropsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trace_transport.driver_id
     *
     * @return the value of trace_transport.driver_id
     *
     * @mbg.generated Tue Nov 03 22:03:31 CST 2020
     */
    public String getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trace_transport.driver_id
     *
     * @param driverId the value for trace_transport.driver_id
     *
     * @mbg.generated Tue Nov 03 22:03:31 CST 2020
     */
    public void setDriverId(String driverId) {
        this.driverId = driverId == null ? null : driverId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trace_transport.time
     *
     * @return the value of trace_transport.time
     *
     * @mbg.generated Tue Nov 03 22:03:31 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trace_transport.time
     *
     * @param time the value for trace_transport.time
     *
     * @mbg.generated Tue Nov 03 22:03:31 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trace_transport.farmer_nick_name
     *
     * @return the value of trace_transport.farmer_nick_name
     *
     * @mbg.generated Tue Nov 03 22:03:31 CST 2020
     */
    public String getFarmerNickName() {
        return farmerNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trace_transport.farmer_nick_name
     *
     * @param farmerNickName the value for trace_transport.farmer_nick_name
     *
     * @mbg.generated Tue Nov 03 22:03:31 CST 2020
     */
    public void setFarmerNickName(String farmerNickName) {
        this.farmerNickName = farmerNickName == null ? null : farmerNickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trace_transport.farmer_user_name
     *
     * @return the value of trace_transport.farmer_user_name
     *
     * @mbg.generated Tue Nov 03 22:03:31 CST 2020
     */
    public String getFarmerUserName() {
        return farmerUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trace_transport.farmer_user_name
     *
     * @param farmerUserName the value for trace_transport.farmer_user_name
     *
     * @mbg.generated Tue Nov 03 22:03:31 CST 2020
     */
    public void setFarmerUserName(String farmerUserName) {
        this.farmerUserName = farmerUserName == null ? null : farmerUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trace_transport.status
     *
     * @return the value of trace_transport.status
     *
     * @mbg.generated Tue Nov 03 22:03:31 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trace_transport.status
     *
     * @param status the value for trace_transport.status
     *
     * @mbg.generated Tue Nov 03 22:03:31 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trace_transport.remarks
     *
     * @return the value of trace_transport.remarks
     *
     * @mbg.generated Tue Nov 03 22:03:31 CST 2020
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trace_transport.remarks
     *
     * @param remarks the value for trace_transport.remarks
     *
     * @mbg.generated Tue Nov 03 22:03:31 CST 2020
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    @Override
    public String toString() {
        return "TraceTransport{" +
                "id=" + id +
                ", cropsId='" + cropsId + '\'' +
                ", driverId='" + driverId + '\'' +
                ", time=" + time +
                ", farmerNickName='" + farmerNickName + '\'' +
                ", farmerUserName='" + farmerUserName + '\'' +
                ", farmerTel='" + farmerTel + '\'' +
                ", farmerDept='" + farmerDept + '\'' +
                ", status=" + status +
                ", outFactoryStatus=" + outFactoryStatus +
                ", remarks='" + remarks + '\'' +
                '}';
    }
}