package com.ruoyi.traces.domain;

public class TraceLngLat {

    private Long id;

    private Float lng;

    private Float lat;

    private String cropsId;

    private int status;

    private int outFactoryStatus;

    @Override
    public String toString() {
        return "TraceLngLat{" +
                "id=" + id +
                ", lng=" + lng +
                ", lat=" + lat +
                ", cropsId='" + cropsId + '\'' +
                ", status=" + status +
                ", outFactoryStatus=" + outFactoryStatus +
                '}';
    }

    public int getOutFactoryStatus() {
        return outFactoryStatus;
    }

    public void setOutFactoryStatus(int outFactoryStatus) {
        this.outFactoryStatus = outFactoryStatus;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trace_lng_lat.id
     *
     * @param id the value for trace_lng_lat.id
     *
     * @mbg.generated Fri Nov 06 19:35:15 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trace_lng_lat.lng
     *
     * @return the value of trace_lng_lat.lng
     *
     * @mbg.generated Fri Nov 06 19:35:15 CST 2020
     */
    public Float getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trace_lng_lat.lng
     *
     * @param lng the value for trace_lng_lat.lng
     *
     * @mbg.generated Fri Nov 06 19:35:15 CST 2020
     */
    public void setLng(Float lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trace_lng_lat.lat
     *
     * @return the value of trace_lng_lat.lat
     *
     * @mbg.generated Fri Nov 06 19:35:15 CST 2020
     */
    public Float getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trace_lng_lat.lat
     *
     * @param lat the value for trace_lng_lat.lat
     *
     * @mbg.generated Fri Nov 06 19:35:15 CST 2020
     */
    public void setLat(Float lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trace_lng_lat.crops_id
     *
     * @return the value of trace_lng_lat.crops_id
     *
     * @mbg.generated Fri Nov 06 19:35:15 CST 2020
     */
    public String getCropsId() {
        return cropsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trace_lng_lat.crops_id
     *
     * @param cropsId the value for trace_lng_lat.crops_id
     *
     * @mbg.generated Fri Nov 06 19:35:15 CST 2020
     */
    public void setCropsId(String cropsId) {
        this.cropsId = cropsId == null ? null : cropsId.trim();
    }
}